name: Test

on:
  push:
    branches: [ main ]
    tags: ["v*"]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - run: git fetch --prune --unshallow --tags
    - uses: extractions/setup-just@v3
    - uses: actions/setup-go@v5
      with:
        go-version: "1.24"
        check-latest: true
        cache: true
    - name: test
      run: just test
